In [2]:
import torch
import numpy as np

In [4]:
data = [[1, 2], [3, 4]]

# tensor from data
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [7]:
# tensor from ndarray
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [8]:
# tensor from another tensor
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [10]:
# from random or constant values
shape = (2, 3, 5)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random tensor: \n {rand_tensor} \n")
print(f"Ones tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random tensor: 
 tensor([[[0.1837, 0.9724, 0.6352, 0.2716, 0.7969],
         [0.6312, 0.8828, 0.3888, 0.7170, 0.8618],
         [0.5983, 0.8006, 0.2029, 0.0742, 0.5458]],

        [[0.1476, 0.0216, 0.8464, 0.9800, 0.9604],
         [0.9890, 0.0649, 0.2091, 0.8096, 0.1972],
         [0.5381, 0.9166, 0.0514, 0.8360, 0.3560]]]) 

Ones tensor: 
 tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]) 

Zeros Tensor: 
 tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])


In [11]:
# Tensor attributes
# shape, data types and device on which tensor is stored

tensor = torch.rand(4, 3)
print(f"Tensor shape: {tensor.shape}")
print(f"Tensor data type: {tensor.dtype}")
print(f"Tensor device: {tensor.device}")


Tensor shape: torch.Size([4, 3])
Tensor data type: torch.float32
Tensor device: cpu


In [14]:
# moving tenso to GPU
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Tensor device: {tensor.device}")

Tensor device: cuda:0


In [26]:
# indexing and slicing
tensor = torch.rand(4, 4)
print(f"{tensor} \n ")
print('First row: ', tensor[0]) 
print('First Column: ', tensor[:, 0]) # : is for all rows, 0 is for first column
print('Last Column: ', tensor[..., -1]) # ... means all dimensions, same as [:, -1]

tensor([[0.3589, 0.2130, 0.6490, 0.4627],
        [0.4530, 0.5703, 0.4604, 0.2263],
        [0.6211, 0.9304, 0.4605, 0.7614],
        [0.2694, 0.0336, 0.7533, 0.4155]]) 
 
First row:  tensor([0.3589, 0.2130, 0.6490, 0.4627])
First Column:  tensor([0.3589, 0.4530, 0.6211, 0.2694])
Last Column:  tensor([0.4627, 0.2263, 0.7614, 0.4155])


In [28]:
# joining tensors
t1 = torch.cat([tensor, tensor], dim=1)
print(f"{t1} \n")

tensor([[0.3589, 0.2130, 0.6490, 0.4627, 0.3589, 0.2130, 0.6490, 0.4627],
        [0.4530, 0.5703, 0.4604, 0.2263, 0.4530, 0.5703, 0.4604, 0.2263],
        [0.6211, 0.9304, 0.4605, 0.7614, 0.6211, 0.9304, 0.4605, 0.7614],
        [0.2694, 0.0336, 0.7533, 0.4155, 0.2694, 0.0336, 0.7533, 0.4155]]) 



In [32]:
# Arthimetical operations
# Matrix multiplication (3 diffrent ways) y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

print(f"y1: {y1} \n y2: {y2} \n y3: {y3}")

# dot multiplication, element wise multiplication (3 diffrent ways)
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print(f"z1: {z1} \n z2: {z2} \n z3: {z3}")



y1: tensor([[0.8096, 0.6876, 1.0724, 0.7850],
        [0.6876, 0.7937, 1.1963, 0.5820],
        [1.0724, 1.1963, 2.0433, 0.8619],
        [0.7850, 0.5820, 0.8619, 0.8138]]) 
 y2: tensor([[0.8096, 0.6876, 1.0724, 0.7850],
        [0.6876, 0.7937, 1.1963, 0.5820],
        [1.0724, 1.1963, 2.0433, 0.8619],
        [0.7850, 0.5820, 0.8619, 0.8138]]) 
 y3: tensor([[0.8096, 0.6876, 1.0724, 0.7850],
        [0.6876, 0.7937, 1.1963, 0.5820],
        [1.0724, 1.1963, 2.0433, 0.8619],
        [0.7850, 0.5820, 0.8619, 0.8138]])
z1: tensor([[0.1288, 0.0454, 0.4212, 0.2141],
        [0.2052, 0.3253, 0.2120, 0.0512],
        [0.3858, 0.8657, 0.2121, 0.5797],
        [0.0726, 0.0011, 0.5674, 0.1727]]) 
 z2: tensor([[0.1288, 0.0454, 0.4212, 0.2141],
        [0.2052, 0.3253, 0.2120, 0.0512],
        [0.3858, 0.8657, 0.2121, 0.5797],
        [0.0726, 0.0011, 0.5674, 0.1727]]) 
 z3: tensor([[0.1288, 0.0454, 0.4212, 0.2141],
        [0.2052, 0.3253, 0.2120, 0.0512],
        [0.3858, 0.8657, 0.2121, 0.5797

In [33]:
# converting a single-element tensor to a Python numerical value
agg = tensor.sum() # sum of all elements, (aggregation operation)
agg_item = agg.item()
print(agg_item, type(agg_item))

7.639002799987793 <class 'float'>


In [35]:
# In place operations
# They are denoted by a trailing underscore (_ as suffix)
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[5.3589, 5.2130, 5.6490, 5.4627],
        [5.4530, 5.5703, 5.4604, 5.2263],
        [5.6211, 5.9304, 5.4605, 5.7614],
        [5.2694, 5.0336, 5.7533, 5.4155]]) 

tensor([[10.3589, 10.2130, 10.6490, 10.4627],
        [10.4530, 10.5703, 10.4604, 10.2262],
        [10.6211, 10.9304, 10.4605, 10.7614],
        [10.2694, 10.0336, 10.7533, 10.4155]])
